### ISSUE TITLE
It does not work anymore

### ISSUE THREAD

**Issue by 123aezakmi123** [NoMod-Programming/PearsonEbookDownloader#1]
Error code:
`Downloading metadata and eText information...`
`Traceback (most recent call last):`
 ` File "downloader.py", line 171, in <module>`
  `  main(sys.argv[1])`
  `File "downloader.py", line 39, in main`
   ` bookInfoGetUrl = bookInfoUrl.format(bookData["bookid"][0])`
`KeyError: 'bookid'`

**Comment by NoMod-Programming** [comment]
That error is saying that the download script can't find a `bookid` GET parameter. Does your book URL have one? Additionally, what's the domain that the eText is loading from?

**Comment by 123aezakmi123** [comment]
I use a link like this
`http://view.ebookplus.pearsoncmg.com/ebook/launcheText.do?values=scenario::16::languageid::4::global::Y::platform::1116::bookID::101417::scenario::16::invokeType::lms::launchState::goToEBook::platform::1116::languageid::4::globalBookID::CM55029655::userID::257XXXX::scenario::16::scenarioid::scenario16::sessionID::ST-XXXXXXX-hG5fLm57sixXXXXXXXXX-b3-rumba-prod-01-01::smsUserID::ffffffff57ee840deXXXXXXXXXXXXXXX::uid::20160XXXXXXXXX::ubd::2018XXXXXXXXX::ubsd::20181XXXXXXXXX::hsid::61a92ae92d67b9XXXXXXXXXXXXXXXXXX`

**Comment by NoMod-Programming** [comment]
Ah, I'm seeing the issue now. Your URL seems to be using colons as separators (not sure if this is because of the copy and paste of the URL or if it's just like that for whatever reason), and bookID and userID are capitalized (and `roletypeid` is missing). The only thing stopping me from fixing this right now is trying to find a `roletypeid` parameter in that request string. I'm currently looking through pearson's javascript to figure it out, and I'll hopefully have it fixed by tomorrow. Sorry for any delays.

**Comment by NoMod-Programming** [comment]
Alright, I've just pushed a commit that should fix the issue. Let me know if it works, and if so, I'll close the issue.

**Comment by 123aezakmi123** [comment]
Now the error is
`Downloading metadata and eText information...`
`Traceback (most recent call last):`
`  File "downloader.py", line 205, in <module>`
`    main(sys.argv[1])`
`  File "downloader.py", line 88, in main`
`    pageInfo = pageInfo[0]['pdfPlayerPageInfoTOList']`
`KeyError: 0`
If you want, I can send you an email with the complete link of the book

**Comment by NoMod-Programming** [comment]
Sure, that'd be helpful. My email is epedemont@icloud.com.

**Comment by degroffr** [comment]
I just got the same error, but I think it may be because the link format is different? I used a link like this:

https://etext.pearson.com/eplayer/book/3KWIB63Q55F/page/a909e4ee046241fe17bffc3da933fc8510f3f8f96-id_toc17?platforms_id=mastering&b=3KWIB63Q55F&idpName=SMS&contextId=bond52756&smsUserId=84775567&courseName=PCB3063+Genetics+F2F+SP19+Large&tool_consumer_instance_guid=etext2.0&lti_message_type=basic-lti-launch-request&lti_version=LTI-1p0&isPrintPage=false&custom_bookid=3KWIB63Q55F&context_id=bond52756&custom_course_name=PCB3063+Genetics+F2F+SP19+Large&custom_displaycourseid=MGENCCNG70807&custom_smsid=84775567&role=cd73502828457d15655bbd7a63fb0bc8yc&custom_error_url=https%3A%2F%2Fsession.masteringgenetics.com%2Fmyct%2FeBookPurchase%3FbookCode%3Dklug12&productModel=ETEXT2_PXE&isDeeplink=true&key=20356102691419329890102019&deeplink=true&pageNo=17&launchLocale=en-us

**Comment by jammibravau** [comment]
Hey just tried using your tool and received "KeyError: 'bookid'" please see below for the URL which I used to access my textbook. Any help would be appreciated!

https://etext.pearson.com/eplayer/book/FKLP4K4IB0L/page/a16eebc6cc818ae42be0e3a2d77f354988b34efd8-P7001013785000000000000000000694?deeplink=true&platforms_id=platform-11&idpName=SMS&isPrintPage=false&launchLocale=en-us&productModel=ETEXT2_PXE&isDeeplink=true&token=9309141781444469121252019&bookId=FKLP4K4IB0L&pageNo=11&pageId=?deeplink

**Comment by 123aezakmi123** [comment]
<img width="900" alt="issue-github" src="https://user-images.githubusercontent.com/44506505/54343201-98623380-463e-11e9-83fb-3b8c74212305.png">

The PDF path doesn't exist, it's impossible to download the pages

**Comment by NoMod-Programming** [comment]
It's not impossible to download the eBooks, as the ETEXT2_PXE style books come from an epub file. I've got code to download the relevant ePub from Pearson's servers, and converting it to a PDF is about as easy as running it through phantomjs's render.js script (plus some small changes to links to make them work properly. Within a few days, I'll push out an update that'll support the newer style books.

**Comment by NoMod-Programming** [comment]
I've created a new issue for all ETEXT2_PXE-style books. At the moment, they're unsupported because they use a completely different format compared to the original etext system this downloader works with. Closed to keep discussion on these types of books in #12
